insert into ordeals (name_en, name_uk, unit_en, unit_uk) values
  ('Running', 'Біг', 'km', 'км'),
  ('Cycling', 'Велосипед', 'km', 'км'),
  ('Swimming', 'Плавання', 'km', 'км'),
  ('Hiking', 'Похід', 'km', 'км'),
  ('Steps walked', 'Пройдені кроки', 'steps', 'кроки'),
  ('Push-ups', 'Віджимання', 'reps', 'рази'),
  ('Pull-ups', 'Підтягування', 'reps', 'рази'),
  ('Gym sessions', 'Походи в зал', 'sessions', 'тренування'),
  ('Climbing routes', 'Скелелазні траси', 'routes', 'траси'),
  ('Cold showers', 'Крижані душі', 'showers', 'душі'),
  ('Chess victories', 'Шахові звитяги', 'wins', 'перемоги'),
  ('Board game victories', 'Звитяги в настолках', 'wins', 'перемоги'),
  ('Poker nights won', 'Виграні покерні вечори', 'wins', 'перемоги'),
  ('Darts victories', 'Звитяги в дартс', 'wins', 'перемоги'),
  ('Bowling victories', 'Звитяги в боулінг', 'wins', 'перемоги'),
  ('Billiards victories', 'Звитяги в більярд', 'wins', 'перемоги'),
  ('Table tennis victories', 'Звитяги в настільний теніс', 'wins', 'перемоги'),
  ('Mario Kart victories', 'Перемоги в Mario Kart', 'wins', 'перемоги'),
  ('FIFA victories', 'Перемоги у FIFA', 'wins', 'перемоги'),
  ('Pages read', 'Прочитані сторінки', 'pages', 'сторінки'),
  ('Books finished', 'Дочитані книги', 'books', 'книги'),
  ('Words written', 'Написані слова', 'words', 'слова'),
  ('Fish caught', 'Спіймана риба', 'fish', 'рибини'),
  ('Sunrises witnessed', 'Зустрінуті світанки', 'sunrises', 'світанки'),
  ('Saunas endured', 'Пережиті сауни', 'saunas', 'сауни'),
  ('Concerts survived', 'Пережиті концерти', 'concerts', 'концерти'),
  ('Countries visited', 'Відвідані країни', 'countries', 'країни'),
  ('Cities conquered', 'Підкорені міста', 'cities', 'міста'),
  ('Beer drunk', 'Випите пиво', 'liters', 'літри'),
  ('Coffee drunk', 'Випита кава', 'cups', 'чашки'),
  ('Pizzas devoured', 'Поглинуті піци', 'pizzas', 'піци'),
  ('Varenyky devoured', 'Поглинуті вареники', 'pieces', 'штуки'),
  ('Days without sugar', 'Дні без цукру', 'days', 'дні'),
  ('Days without alcohol', 'Дні без алкоголю', 'days', 'дні');
