#!/usr/bin/env python3
"""Generate taunt template/bank seed SQL from spec/copy-deck.md section 5.
Words are extracted programmatically -- never retyped -- to preserve UA text."""
import re, pathlib

spec = pathlib.Path(__file__).resolve().parent.parent / 'spec' / 'copy-deck.md'
text = spec.read_text(encoding='utf-8')

def slots_for(header_marker: str) -> list[list[str]]:
    block = text.split(header_marker, 1)[1]
    slots = []
    for line in block.splitlines():
        m = re.match(r'^- Slot \d+: (.+)$', line.strip())
        if m:
            slots.append([w.strip() for w in m.group(1).split('·')])
        elif slots and line.strip() == '':
            break
    return slots

en_slots = slots_for('**EN template 1**')
uk_slots = slots_for('**UA template 1**')
assert len(en_slots) == 4 and len(uk_slots) == 4, (len(en_slots), len(uk_slots))
assert en_slots[0][0] == 'Thy' and uk_slots[0][0] == 'Твоє'

def esc(w: str) -> str:
    return w.replace("'", "''")

out = ["-- GENERATED by scripts/gen-taunt-seed.py from spec/copy-deck.md section 5. Do not hand-edit words."]
for lang, slots in (('en', en_slots), ('uk', uk_slots)):
    var = f'tpl_{lang}'
    out.append(f"""
do $$
declare {var} uuid;
begin
  insert into taunt_templates (language, skeleton, slot_count)
  values ('{lang}', '{{0}} {{1}} {{2}} {{3}}.', 4)
  returning id into {var};""")
    for si, words in enumerate(slots):
        for wi, w in enumerate(words):
            out.append(f"  insert into taunt_banks (template_id, slot_index, word_index, word) values ({var}, {si}, {wi}, '{esc(w)}');")
    out.append("end $$;")

print('\n'.join(out))
