-- GENERATED by scripts/gen-taunt-seed.py from spec/copy-deck.md section 5. Do not hand-edit words.

do $$
declare tpl_en uuid;
begin
  insert into taunt_templates (language, skeleton, slot_count)
  values ('en', '{0} {1} {2} {3}.', 4)
  returning id into tpl_en;
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 0, 0, 'Thy');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 0, 1, 'Your');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 0, 2, 'That');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 0, 3, 'Behold, thy');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 0, 4, 'Even thy');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 0, 'pitiful');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 1, 'trembling');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 2, 'rusted');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 3, 'feeble');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 4, 'doomed');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 5, 'legendary-in-rumor-only');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 6, 'moss-covered');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 7, 'saga-less');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 8, 'mead-soaked');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 9, 'flea-bitten');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 1, 10, 'thrall-worthy');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 0, 'effort');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 1, 'progress');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 2, 'discipline');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 3, 'ambition');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 4, 'legacy');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 5, 'spirit');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 6, 'so-called record');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 7, 'attempt');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 8, 'technique');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 2, 9, 'tower');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 0, 'crumbles before me');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 1, 'feeds the crows');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 2, 'shames thy ancestors');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 3, 'is but a rumor');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 4, 'withers at dawn');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 5, 'amuses my crows');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 6, 'would shame a thrall');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 7, 'shall be sung of in no saga');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 8, 'would not frighten a sheep');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 9, 'melts like snow in spring');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 10, 'is mocked in three villages');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 11, 'belongs in the pig pen');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_en, 3, 12, 'would lose to a turnip');
end $$;

do $$
declare tpl_uk uuid;
begin
  insert into taunt_templates (language, skeleton, slot_count)
  values ('uk', '{0} {1} {2} {3}.', 4)
  returning id into tpl_uk;
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 0, 0, 'Твоє');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 0, 1, 'Оте');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 0, 2, 'Се');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 0, 3, 'Навіть твоє');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 0, 'жалюгідне');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 1, 'тремтливе');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 2, 'іржаве');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 3, 'немічне');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 4, 'приречене');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 5, 'трухляве');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 6, 'миршаве');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 7, 'замшіле');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 8, 'скисле');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 1, 9, 'безславне');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 0, 'махання фігурами');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 1, 'тупцювання');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 2, 'вежування');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 3, 'тренування');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 4, 'так зване досягнення');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 5, 'старання');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 6, 'ремесло');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 2, 7, 'надбання');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 0, 'розсипається переді мною');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 1, 'годує ворон');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 2, 'ганьбить твій рід');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 3, 'є лише чутками');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 4, 'в''яне на світанку');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 5, 'смішить навіть курей');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 6, 'не налякає й горобця');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 7, 'не варте й дірки з бублика');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 8, 'розвіється, як дим над тином');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 9, 'зів''яне, як трава під косою');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 10, 'не варте й ламаного гроша');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 11, 'славиться хіба в поговорах');
  insert into taunt_banks (template_id, slot_index, word_index, word) values (tpl_uk, 3, 12, 'програло б і гарбузові');
end $$;

create or replace function send_taunt(p_feud_id uuid, p_template_id uuid, p_picks int[])
returns taunts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_feud feuds;
  v_slot_count int;
  v_bank_size int;
  v_taunt taunts;
  i int;
begin
  if auth.uid() is null then
    raise exception 'auth_required';
  end if;
  select * into v_feud from feuds where id = p_feud_id;
  if not found or auth.uid() not in (v_feud.profile_a, v_feud.profile_b) then
    raise exception 'not_member';
  end if;
  if v_feud.status <> 'active' then
    raise exception 'feud_not_active';
  end if;
  select slot_count into v_slot_count from taunt_templates where id = p_template_id;
  if not found then
    raise exception 'bad_template';
  end if;
  if p_picks is null or array_length(p_picks, 1) <> v_slot_count then
    raise exception 'bad_picks';
  end if;
  for i in 0 .. v_slot_count - 1 loop
    select count(*) into v_bank_size from taunt_banks
    where template_id = p_template_id and slot_index = i;
    if p_picks[i + 1] < 0 or p_picks[i + 1] >= v_bank_size then
      raise exception 'bad_picks';
    end if;
  end loop;

  begin
    insert into taunts (feud_id, author, template_id, picks)
    values (p_feud_id, auth.uid(), p_template_id, p_picks)
    returning * into v_taunt;
  exception when unique_violation then
    raise exception 'taunt_spent';
  end;
  return v_taunt;
end;
$$;

revoke execute on function send_taunt(uuid, uuid, int[]) from public;
grant execute on function send_taunt(uuid, uuid, int[]) to authenticated;

alter publication supabase_realtime add table taunts;
